input_data_path: './data/raw/train.csv'
output_model_path: './models/model.pkl'
metric_path: './models/metrics.json'
downloading_params:
  use_download: False
  s3_bucket: 'made-mlprod-hw1'
  endpointurl: 'https://ib.bizmrg.com'
  paths: 
    - 'train.csv'
    - 'test.csv'
  output_folder: './data/raw/'
splitting_params:
  val_size: 0.1
  random_state: 42
mlflow:
  use_mlflow: False
  mlflow_uri: 'http://127.0.0.1:5001'
  mlflow_experiment: 'test'
